import nodemailer from 'nodemailer';

export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ message: 'Method Not Allowed' });
    }

    const {
        firstName,
        lastName,
        email,
        phone,
        requirements,
        formType
    } = req.body;

    // Validate basic fields
    if (!email || !firstName) {
        return res.status(400).json({ message: 'Email and First Name are required' });
    }

    // Configure the transporter
    // IMPORTANT: User needs to set these in their environment variables (Vercel/Netlify/Local .env)
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS // Use an App Password for Gmail
        }
    });

    // Email content construction
    const mailOptions = {
        from: `"TrueNorth Website" <${process.env.EMAIL_USER}>`,
        to: 'contact@truenorthae.com', // The destination email
        subject: `New Lead: ${formType || 'Contact Form'} - ${firstName} ${lastName || ''}`,
        html: `
            <div style="font-family: 'serif', sans-serif; padding: 20px; color: #18181b; background-color: #fafafa; border-radius: 10px;">
                <h1 style="color: #f97316; font-size: 24px; border-bottom: 2px solid #f97316; padding-bottom: 10px;">New Inquiry Received</h1>
                <p style="font-size: 16px; margin-top: 20px;">You have a new lead from the <strong>${formType || 'General Contact'}</strong> form.</p>
                
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                    <tr style="background-color: #f4f4f5;">
                        <td style="padding: 10px; font-weight: bold; border: 1px solid #e4e4e7;">Name:</td>
                        <td style="padding: 10px; border: 1px solid #e4e4e7;">${firstName} ${lastName || ''}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; font-weight: bold; border: 1px solid #e4e4e7;">Email:</td>
                        <td style="padding: 10px; border: 1px solid #e4e4e7;"><a href="mailto:${email}">${email}</a></td>
                    </tr>
                    <tr style="background-color: #f4f4f5;">
                        <td style="padding: 10px; font-weight: bold; border: 1px solid #e4e4e7;">Phone:</td>
                        <td style="padding: 10px; border: 1px solid #e4e4e7;">${phone || 'Not provided'}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; font-weight: bold; border: 1px solid #e4e4e7;">Details/Requirements:</td>
                        <td style="padding: 10px; border: 1px solid #e4e4e7;">${requirements || 'No details provided'}</td>
                    </tr>
                </table>
                
                <p style="margin-top: 30px; font-size: 12px; color: #71717a;">This email was automatically generated by the TrueNorth Consulting website.</p>
            </div>
        `
    };

    try {
        await transporter.sendMail(mailOptions);
        return res.status(200).json({ success: true, message: 'Email sent successfully' });
    } catch (error) {
        console.error('Nodemailer Error:', error);
        return res.status(500).json({ success: false, message: 'Failed to send email', error: error.message });
    }
}
